spring:
  application:
    name: PagFut

  datasource:
    url: jdbc:h2:mem:pagfut
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: pagfutsender@gmail.com
    password: wevxojycdornesbl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

api:
  security:
    token:
      secret: mysecret

app:
  frontend:
    base-url: http://localhost:4200/
  backend:
    base-url: http://localhost:8080/

