spring:
  application:
    name: PagFut

  datasource:
    url: jdbc:postgresql://localhost:5433/pagfut
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: pagfutsender@gmail.com
    password: wevxojycdornesbl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com



api:
  security:
    token:
      secret: mysecret

app:
  frontend:
    base-url: http://localhost:4200/
  backend:
    base-url: http://localhost:8080/

